version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    name: 'Checking labels'
    validate:
      - do: label
        must_include:
          regex: 'patch|minor|major|no-release'
          regex_flag: 'none' # Optional. Specify the flag for Regex. default is 'i', to disable default use 'none'
          message: 'Must have a version increment label'
    fail:
      - do: checks # default pass case
        status: 'failure' # Can be: success, failure, neutral, cancelled, timed_out, or action_required
        payload:
          title: 'Must have a version increment or no-release label'
          summary: "All the validators have returned 'pass'! \n Here are some stats of the run: \n {{validationCount}} validations were ran"

  - when: pull_request.opened
    name: "Greet a contributor"
    validate: []
    pass:
      - do: comment
        payload:
          body: >
            Thanks for creating a pull request! A maintainer will review your changes shortly. Please don't be discouraged if it takes a while.
