name: markdown check compliance 

on:
  pull_request:
    branches: main
   
jobs:
        
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    # Analyze Azure resources using PSRule for Azure
    - name: Analyze Azure template files
      uses: microsoft/ps-rule@v2.2.0
      with:
        modules: 'PSRule.Rules.GitHub'
